import csv


def load_kinds_prefix_mapping(file_path: str) -> dict:
    """
    Create a dict {Kind: Prefix} from the CSV generated by mappingUvlCsvK8sOld.py
    Ex:
        {"Pod": "io_k8s_api_core_v1", "RoleBinding": "io_k8s_api_rbac_v1", ...}
    """
    mapping = {}
    with open(file_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kind = row["Kind"].strip()
            prefix = row["Prefix"].strip()
            mapping[kind] = prefix
    return mapping

def load_feature_dict(csv_file="../resources/mapping_csv/kubernetes_mapping_properties_features.csv"):
    feature_dict = {}

    with open(csv_file, newline='', encoding="utf-8") as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            midle = row["Midle"].strip()
            
            # Almacenar en el diccionario usando 'Midle' como clave
            feature_dict[midle] = row

    return feature_dict

def clean_description(description: str) -> str:
    return description.replace('\n', ' ') \
                    .replace('`', '') \
                    .replace('´', '') \
                    .replace("'", "_") \
                    .replace('{', '') \
                    .replace('}', '') \
                    .replace('"', '') \
                    .replace("\\", "_") \
                    .replace(".", "") \
                    .replace("//", "_").replace('\u2019', '_').replace('\u2018', '_') ## ??''' ¡¡¡ ´´ççç`+++`

def get_base_prefix(kind_prefix): ## Used by the generate_uvl_policies
    if kind_prefix == "Pod":
        return "Pod" ## _PodList    PodTemplate  PodTemplateList PodTemplateSpec
    elif "PodList" == kind_prefix:
        return "PodList"
    elif "PodTemplate" == kind_prefix:
        return "PodTemplate"
    elif "PodTemplateList" == kind_prefix:
        return "PodTemplateList"
    elif "PodTemplateSpec" == kind_prefix:
        return "PodTemplateSpec"
    elif "Replicaset" == kind_prefix:
        return "ReplicaSet"
    elif "Replicationcontroller" == kind_prefix:
        return "RepController"
    elif "Deploymentconfig" == kind_prefix:
        return "DeployConfig" 
    elif "Cronjob" == kind_prefix: ## Added for Rego subtypes
        return "CronJob"
    elif "Serviceaccount" in kind_prefix:
        return "ServAcc"
    elif "Service" in kind_prefix:
        return "Serv"
    elif "Clusterolebinding" in kind_prefix:
        return "ClusRole"
    elif "Rolebinding" in kind_prefix:
        return "RoleBinding"
    elif "Ingress" in kind_prefix:
        return "Ingress"
    elif "Job" in kind_prefix:
        return "Job"
    elif "Daemonset" in kind_prefix:
        return "DaemonSet"
    elif "Deployment" in kind_prefix:
        return "Deployment"
    elif "Statefulset" in kind_prefix:
        return "StatefulSet"
    elif "Secret" in kind_prefix:
        return "Secret" # PersistentVolumeClaim
    elif "Persistentvolumeclaim" in kind_prefix:
        return "PersistVolumeClaim" ## PodDisruptionBudgetFeatures
    elif "Poddisruptionbudget" in kind_prefix:
        return "PodDisrupBud"
    else:
        return "Kubernetes"
    

def normalize_kind_name(kind, kind_map):
    """
    Match kind string (rego: lower) to correct official K8s Kind casing.
    Ex: 'cronjob' -> 'CronJob'
    """
    ## kind_prefix_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")
    kind_lower = kind.lower()
    for k in kind_map.keys():
        if k.lower() == kind_lower:
            return k  # Return correctly capitalized e.g. CronJob
    return kind.capitalize()